// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;




/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBqnQq1dXJqy_3nJWBBForwJdiaZSp9FRk',
    appId: '1:1057911539610:web:9eaeeef9b4478145dc9c23',
    messagingSenderId: '1057911539610',
    projectId: 'dieat-28713',
    authDomain: 'dieat-28713.firebaseapp.com',
    storageBucket: 'dieat-28713.appspot.com',
    measurementId: 'G-QLQZW7226V',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCURCBn7UEuvgQEGZm6lf6z2FmQW0p4PIw',
    appId: '1:1057911539610:ios:a143daa21a88a47bdc9c23',
    messagingSenderId: '1057911539610',
    projectId: 'dieat-28713',
    storageBucket: 'dieat-28713.appspot.com',
    iosClientId: '1057911539610-ume8i5fohcgvramp0utq4kdnl88lmle9.apps.googleusercontent.com',
    iosBundleId: 'com.example.dieat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCURCBn7UEuvgQEGZm6lf6z2FmQW0p4PIw',
    appId: '1:1057911539610:ios:a143daa21a88a47bdc9c23',
    messagingSenderId: '1057911539610',
    projectId: 'dieat-28713',
    storageBucket: 'dieat-28713.appspot.com',
    iosClientId: '1057911539610-ume8i5fohcgvramp0utq4kdnl88lmle9.apps.googleusercontent.com',
    iosBundleId: 'com.example.dieat',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBqnQq1dXJqy_3nJWBBForwJdiaZSp9FRk',
    appId: '1:1057911539610:web:d7774df3e4966f42dc9c23',
    messagingSenderId: '1057911539610',
    projectId: 'dieat-28713',
    authDomain: 'dieat-28713.firebaseapp.com',
    storageBucket: 'dieat-28713.appspot.com',
    measurementId: 'G-RE66VH79V0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCmk9ZtrsCwZ2LnlwOBI3CpP4XLTdQ9obI',
    appId: '1:1057911539610:android:1c3b73663f61af0fdc9c23',
    messagingSenderId: '1057911539610',
    projectId: 'dieat-28713',
    storageBucket: 'dieat-28713.appspot.com',
  );

}

